apiVersion: v2
name: dagster-prometheus-exporter
description: A Prometheus exporter for Dagster run metrics
type: application
version: 0.1.1
appVersion: "v0.2.0"
home: https://github.com/HirofumiTsuda/dagster-prometheus-exporter
sources:
  - https://github.com/HirofumiTsuda/dagster-prometheus-exporter
maintainers:
  - name: HirofumiTsuda
    url: https://github.com/HirofumiTsuda
