[project]
name = "dagster-prometheus-exporter"
version = "0.1.0"
description = "A python environment used for tests"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dagster>=1.13.15,<1.14",
    "dagster-webserver>=1.13.15,<1.14",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["dev"]

[tool.dagster]
module_name = "dev.dagster_workspace.definitions"
code_location_name = "dev-dagster-workspace"

[tool.ruff]
target-version = "py312"
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = []