query GetRuns($statuses: [RunStatus!], $updatedAfter: Float, $cursor: String, $limit: Int) {
  runsOrError(filter: { statuses: $statuses, updatedAfter: $updatedAfter }, cursor: $cursor, limit: $limit) {
    __typename
    ... on Runs {
      results {
        runId
        jobName
        status
        creationTime
        updateTime
        endTime
        tags {
          key
          value
        }
        repositoryOrigin {
          repositoryName
          repositoryLocationName
        }
      }
    }
    ... on PythonError {
      message
      stack
    }
    ... on InvalidPipelineRunsFilterError {
      message
    }
  }
}
