query GetDefinitionsRoster {
  repositoriesOrError {
    __typename
    ... on RepositoryConnection {
      nodes {
        name
        location {
          name
        }
        jobs {
          name
        }
        schedules {
          name
          cronSchedule
          scheduleState {
            status
            ticks(limit: 1) {
              status
              timestamp
            }
          }
        }
      }
    }
    ... on PythonError {
      message
      stack
    }
  }
}
